### ISSUE TITLE
Error while wepback build

### ISSUE THREAD

**Issue by YukSeungChan** [catamphetamine/webpack-isomorphic-tools#145]
I'm trying to build react app and when I give nothing for `NODE_ENV` it builds fine. But when `NODE_ENV=production` is given the build fails.

We can't upload `webpack-stat.json` due to it's size.. 

### Version
"webpack": "^2.3.3",
"webpack-isomorphic-tools": "^3.0.3"
"extract-text-webpack-plugin": "^2.1.0"
"css-loader": "^0.28.4"
"style-loader": "^0.18.2"
"postcss-loader": "^2.0.6"
"sass-loader": "^6.0.6"

### Webpack Configuration
```
const path = require('path');

// node env
const NODE_ENV = process.env.NODE_ENV || 'development';
const __PROD__ = NODE_ENV === 'production';
const __DEV__ = !__PROD__;
const __SERVER__ = false;
const __CLIENT__ = true;
const __DEVTOOLS__ = false;

const webpack = require('webpack');

const WebpackToolsPlugin = require('webpack-isomorphic-tools/plugin');

const webpackToolsConfig = require('./webpack.isomorphic');

const webpackToolsPlugin = new WebpackToolsPlugin(webpackToolsConfig).development(__DEV__);

const ExtractTextPlugin = require('extract-text-webpack-plugin');

const srcPath = path.resolve(__dirname, '../src');
const distPath = path.resolve(__dirname, '../dist');
const clientSrc = path.join(srcPath, 'client');
const appSrc = path.join(srcPath, 'app');
const configSrc = path.join(srcPath, 'config');
const clientInclude = [clientSrc, appSrc, configSrc];

// Cache vendor && client javascript on CDN...
const vendor = [
  'react',
  'react-dom',
  'react-router',
  'react-redux',
  'redux',
];

module.exports = {
  target: 'node',
  context: srcPath,
  entry: {
    app: [
      'babel-polyfill/dist/polyfill.js',
      './client/index.js',
    ],
    vendor,
  },
  resolve: {
    extensions: ['.js'],
    modules: [srcPath, 'node_modules'],
  },
  node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
  },
  output: {
    path: distPath,
    filename: '[name].js',
    chunkFilename: '[name]_[hash].js',
    publicPath: '/static/',
  },
  module: {
    rules: [
      // Javascript
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: clientInclude,
      },
      // CSS
      {
        test: /\.css$/,
        loader: 'style-loader!css-loader',
      },
      // SCSS
      {
        test: /\.scss$/,
        include: clientInclude,
        use: [
          {
            loader: 'style-loader',
          },
          {
            loader: 'css-loader',
            options: {
              root: srcPath,
              modules: true,
              importLoaders: 1,
              camelCase: 'dashes',
              localIdentName: '[name]_[local]_[hash:base64:5]',
            },
          },
          {
            loader: 'postcss-loader',
          },
          {
            loader: 'sass-loader',
          },
        ],
      },
      // JSON
      {
        test: /\.json$/,
        loader: 'json-loader',
      },
      // isomorphic
      {
        test: webpackToolsPlugin.regular_expression('images'),
        loader: 'file-loader',
        query: {
          useRelativePath: false,
        },
      },
      {
        test: webpackToolsPlugin.regular_expression('fonts'),
        loader: 'file-loader',
        query: {
          useRelativePath: false,
        },
      },
    ],
  },
  plugins: [
    new webpack.NamedModulesPlugin(),
    new ExtractTextPlugin('[name].css'),
    new webpack.NormalModuleReplacementPlugin(/app\/routes\/static/, 'app/routes/async'),
    new webpack.optimize.CommonsChunkPlugin({
      names: ['vendor', 'manifest'],
      minChunks: Infinity,
    }),
    new webpack.optimize.AggressiveMergingPlugin(),
    new webpack.optimize.MinChunkSizePlugin({ minChunkSize: 10 }),
    new webpack.optimize.UglifyJsPlugin({ compressor: { warnings: false }, comments: /(?:)/ }),
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
    }),
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(NODE_ENV),
      },
      __DEV__,
      __PROD__,
      __SERVER__,
      __CLIENT__,
      __DEVTOOLS__,
    }),
    webpackToolsPlugin,
  ],
  devtool: 'source-map',
};

```

### Webpack Isomorphic Tools Configuration
```
const plugin = require('webpack-isomorphic-tools/plugin');

module.exports = {
  debug: true,
  webpack_assets_file_path: '../webpack-assets.json',
  webpack_stats_file_path: '../webpack-stats.json',
  assets: {
    images: {
      extensions: ['png', 'jpg', 'jpeg', 'gif', 'ico', 'svg'],
    },
    fonts: {
      extensions: ['eot', 'ttf', 'woff', 'woff2'],
    },
    styles: {
      extensions: ['css', 'less', 'scss', 'sass'],
      filter(module, regex, options, log) {
        return options.development
          ? plugin.styleLoaderFilter(module, regex, options, log)
          : regex.test(module.name);
      },
      path(module, options, log) {
        return options.development
          ? plugin.styleLoaderPathExtractor(module, options, log)
          : module.name;
      },
      parser(module, options, log) {
        return options.development
          ? plugin.cssModulesLoaderParser(module, options, log)
          : module.source;
      },
    },
  },
};
```

### Error And Debug messages
```
[webpack-isomorphic-tools/plugin] [debug]   {
  "id": "../node_modules/css-loader/index.js?{\"root\":\"/Users/loup/Workspace/projects/redice/myrics-front/src\",\"modules\":true,\"importLoaders\":1,\"camelCase\":\"dashes\",\"localIdentName\":\"[name]_[local]_[hash:base64:5]\"}!../node_modules/postcss-loader/lib/index.js!../node_modules/sass-loader/lib/loader.js!./app/pages/front/RecentChapters/style.scss",
  "identifier": "/Users/loup/Workspace/projects/redice/myrics-front/node_modules/css-loader/index.js?{\"root\":\"/Users/loup/Workspace/projects/redice/myrics-front/src\",\"modules\":true,\"importLoaders\":1,\"camelCase\":\"dashes\",\"localIdentName\":\"[name]_[local]_[hash:base64:5]\"}!/Users/loup/Workspace/projects/redice/myrics-front/node_modules/postcss-loader/lib/index.js!/Users/loup/Workspace/projects/redice/myrics-front/node_modules/sass-loader/lib/loader.js!/Users/loup/Workspace/projects/redice/myrics-front/src/app/pages/front/RecentChapters/style.scss",
  "name": "../~/css-loader?{\"root\":\"/Users/loup/Workspace/projects/redice/myrics-front/src\",\"modules\":true,\"importLoaders\":1,\"camelCase\":\"dashes\",\"localIdentName\":\"[name]_[local]_[hash:base64:5]\"}!../~/postcss-loader/lib!../~/sass-loader/lib/loader.js!./app/pages/front/RecentChapters/style.scss",
  "index": 1174,
  "index2": 1166,
  "size": 337,
  "cacheable": true,
  "built": true,
  "optional": false,
  "prefetched": false,
  "chunks": [
    0
  ],
  "assets": [],
  "issuer": "/Users/loup/Workspace/projects/redice/myrics-front/node_modules/style-loader/index.js!/Users/loup/Workspace/projects/redice/myrics-front/node_modules/css-loader/index.js??ref--2-1!/Users/loup/Workspace/projects/redice/myrics-front/node_modules/postcss-loader/lib/index.js!/Users/loup/Workspace/projects/redice/myrics-front/node_modules/sass-loader/lib/loader.js!/Users/loup/Workspace/projects/redice/myrics-front/src/app/pages/front/RecentChapters/style.scss",
  "issuerId": "./app/pages/front/RecentChapters/style.scss",
  "issuerName": "./app/pages/front/RecentChapters/style.scss",
  "failed": false,
  "errors": 0,
  "warnings": 0,
  "reasons": [
    {
      "moduleId": "./app/pages/front/RecentChapters/style.scss",
      "moduleIdentifier": "/Users/loup/Workspace/projects/redice/myrics-front/node_modules/style-loader/index.js!/Users/loup/Workspace/projects/redice/myrics-front/node_modules/css-loader/index.js??ref--2-1!/Users/loup/Workspace/projects/redice/myrics-front/node_modules/postcss-loader/lib/index.js!/Users/loup/Workspace/projects/redice/myrics-front/node_modules/sass-loader/lib/loader.js!/Users/loup/Workspace/projects/redice/myrics-front/src/app/pages/front/RecentChapters/style.scss",
      "module": "./app/pages/front/RecentChapters/style.scss",
      "moduleName": "./app/pages/front/RecentChapters/style.scss",
      "type": "cjs require",
      "userRequest": "!!../../../../../node_modules/css-loader/index.js??ref--2-1!../../../../../node_modules/postcss-loader/lib/index.js!../../../../../node_modules/sass-loader/lib/loader.js!./style.scss",
      "loc": "4:14-207"
    }
  ],
  "usedExports": true,
  "providedExports": null,
  "depth": 8,
  "source": "exports = module.exports = require(\"../../../../../node_modules/css-loader/lib/css-base.js\")(undefined);\n// imports\n\n\n// module\nexports.push([module.id, \".style_slider-dots_14yk_ {\\n  bottom: 5px !important; }\\n\", \"\"]);\n\n// exports\nexports.locals = {\n\t\"slider-dots\": \"style_slider-dots_14yk_\",\n\t\"sliderDots\": \"style_slider-dots_14yk_\"\n};"
}
[webpack-isomorphic-tools/plugin] [error] Error: More than a single candidate module was found in webpack stats for require()d path "!!../../../../../node_modules/css-loader/index.js??ref--2-1!../../../../../node_modules/postcss-loader/lib/index.js!../../../../../node_modules/sass-loader/lib/loader.js!./style.scss". Enable "debug: true" flag in webpack-isomorphic-tools configuration for more info.
    at fail (/Users/loup/Workspace/projects/redice/myrics-front/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/plugin/write assets.js:488:11)
    at /Users/loup/Workspace/projects/redice/myrics-front/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/plugin/write assets.js:496:5
    at resolver (/Users/loup/Workspace/projects/redice/myrics-front/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:150:19)
    at Function._module2.default._findPath (/Users/loup/Workspace/projects/redice/myrics-front/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:469:25)
    at Function.Module._resolveFilename (module.js:467:25)
    at Function._module2.default._resolveFilename (/Users/loup/Workspace/projects/redice/myrics-front/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:442:34)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/loup/Workspace/projects/redice/myrics-front/src/app/pages/front/RecentChapters/style.scss.webpack-module:5:15)
    at Module._compile (module.js:570:32)
    at Object._module2.default._extensions.(anonymous function) [as .webpack-module] (/Users/loup/Workspace/projects/redice/myrics-front/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:280:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at safe_require (/Users/loup/Workspace/projects/redice/myrics-front/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/plugin/write assets.js:656:10)
    at populate_assets (/Users/loup/Workspace/projects/redice/myrics-front/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/plugin/write assets.js:622:32)
    at write_assets (/Users/loup/Workspace/projects/redice/myrics-front/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/plugin/write assets.js:102:2)
    at Compiler.<anonymous> (/Users/loup/Workspace/projects/redice/myrics-front/node_modules/webpack-isomorphic-tools/source/plugin/plugin.js:186:19)
    at Compiler.applyPlugins (/Users/loup/Workspace/projects/redice/myrics-front/node_modules/webpack/node_modules/tapable/lib/Tapable.js:61:14)
    at /Users/loup/Workspace/projects/redice/myrics-front/node_modules/webpack/lib/Compiler.js:271:13
    at Compiler.emitRecords (/Users/loup/Workspace/projects/redice/myrics-front/node_modules/webpack/lib/Compiler.js:367:37)
    at /Users/loup/Workspace/projects/redice/myrics-front/node_modules/webpack/lib/Compiler.js:265:12
    at /Users/loup/Workspace/projects/redice/myrics-front/node_modules/webpack/lib/Compiler.js:360:11
    at next (/Users/loup/Workspace/projects/redice/myrics-front/node_modules/webpack/node_modules/tapable/lib/Tapable.js:154:11)
    at Compiler.compiler.plugin (/Users/loup/Workspace/projects/redice/myrics-front/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/loup/Workspace/projects/redice/myrics-front/node_modules/webpack/node_modules/tapable/lib/Tapable.js:158:13)
    at Compiler.afterEmit (/Users/loup/Workspace/projects/redice/myrics-front/node_modules/webpack/lib/Compiler.js:357:8)
```

**Comment by halt-hammerzeit** [comment]
The error says

> [webpack-isomorphic-tools/plugin] [error] Error: More than a single candidate module was found in webpack stats for require()d path "!!../../../../../node_modules/css-loader/index.js??ref--2-1!../../../../../node_modules/postcss-loader/lib/index.js!../../../../../node_modules/sass-loader/lib/loader.js!./style.scss". Enable "debug: true" flag in webpack-isomorphic-tools configuration for more info.

This kind of errors is unobvious and I usually don't look into them.
One suggestion is to comment out plugins for production to see if there's a plugin that causes the error.
Another way would be migrating to `universal-webpack`.
That's as much as I can say here.
Leaving the issue open just to indicate that such issues exist.

**Comment by YukSeungChan** [comment]
I solved errors when I migrate to `universal-wepack`. Thanks.
