### ISSUE TITLE
Keep getting errors module not defined and exports not defined

### ISSUE THREAD

**Issue by rahulbasu710** [catamphetamine/webpack-isomorphic-tools#148]
Loved the library! I am setting up a standard webpack ReactJS server and am insistent on using webpack-isomorphic-tools to universal-webpack due to the simplicity in steps.

But I got stuck after build (which successfully completed) while it is running on server PORT 8080 NODE_ENV=production but I guess it is a babel compatibility issue. Could you please help?

Thanks!

.babelrc
```
{
  "presets": ["react", ['es2015', { modules: false }], "stage-0"],
  "plugins": ["css-modules-transform"]
}
```

package.json
```
"scripts": {
    "start:dev": "npm run build && NODE_ENV=production PORT=8080 babel-node server.js --presets es2015,react,stage-0",
    "build": "rimraf dist && NODE_ENV=production webpack",
  },
```

server.js
```
import React from 'react';
import express from 'express';
import morgan from 'morgan';
import compression from 'compression';
import helmet from 'helmet';
import hpp from 'hpp';
import WebpackIsomorphicTools from 'webpack-isomorphic-tools';
import { renderToStaticMarkup } from 'react-dom/server';
import Html from './src/Html';
import AppComponent from './src/App';

const isDev = process.env.NODE_ENV !== 'production';
const host = process.env.HOST || 'localhost';
const port = process.env.PORT;
const app = express();

app.use(helmet());
app.use(hpp()); // Prevent HTTP parameter pollution
app.use(compression()); // Compress all requests
app.use(morgan('dev', { skip: (req, res) => res.statusCode < 400 }));
const webpackIsomorphic = new WebpackIsomorphicTools(require('./WIT.config.js'))
.server(require('path').resolve(__dirname), () => {
  require('./server');
});

if (isDev) {
  const webpack = require('webpack');
  const webpackconfig = require('./webpack.config.js');
  app.use(require('webpack-dev-middleware')(webpack(webpackconfig), {
    publicPath: webpackconfig.output.publicPath,
    hot: true,
    noInfo: true,
    stats: 'errors-only',
  }));
  app.use(require('webpack-hot-middleware')(webpack(webpackconfig)));
} else {
  app.use(express.static('dist'));
  app.get('*', (req, res) => {
    if (isDev) {
      webpackIsomorphic.refresh();
    }
    const renderHtml = () => {
      const html = renderToStaticMarkup(<Html assets={webpackIsomorphic.assets()} component={AppComponent} />);
      return `<!doctype html>${html}`;
    };
    res.send(renderHtml());
    // res.sendFile(path.join(__dirname, 'dist/index.html'));
  });
}

if (port) {
  app.listen(port, host, (err) => {
    if (err) console.log(err);
    console.info(`==> 🌎 Listening on http://${host}:${port}`);
  });
} else {
  console.info('==> 😭  OMG!!! No PORT environment variable has been specified');
}
```

webpack.config.js
```
const path = require('path');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const nodeExternals = require('webpack-node-externals');

const nodeEnv = process.env.NODE_ENV || 'development';
const isDev = nodeEnv !== 'production';
const WebpackIsomorphicToolsPlugin = require('webpack-isomorphic-tools/plugin');
const webpackIsomorphicToolsPlugin = new WebpackIsomorphicToolsPlugin(require('./WIT.config')).development(isDev);

const VENDORS = [
  'lodash',
  'react',
  'react-dom',
  'react-redux',
  'react-router',
  'redux',
  'redux-thunk',
];

module.exports = {
  context: path.join(process.cwd()),
  entry: {
    build: './server.js',
    vendor: VENDORS,
  },
  target: 'node',
  output: {
    path: path.join(__dirname, 'dist'),
    filename: isDev ? '[name].js' : '[name].[hash].js',
    publicPath: '/',
  },
  externals: [nodeExternals({
    // Load non-javascript files with extensions, presumably via loaders
    whitelist: [/\.(?!(?:jsx?|json)$).{1,5}$/i],
  })],
  plugins: isDev ? [
    webpackIsomorphicToolsPlugin,
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.HotModuleReplacementPlugin(), // only for dev env
    new ExtractTextPlugin('[name].css'),
    new HtmlWebpackPlugin({ template: 'src/index.html' }),
  ] : [
    webpackIsomorphicToolsPlugin,
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.optimize.CommonsChunkPlugin({ names: ['vendor', 'manifest'], minChunks: Infinity }),
    new ExtractTextPlugin('[name].[chunkhash].css'),
    new HtmlWebpackPlugin({ template: 'src/index.html' }),
    new webpack.optimize.UglifyJsPlugin({ // only for production env
      compressor: {
        warnings: false,
        screw_ie8: true,
      },
    }),
  ],
  module: {
    rules: [
      {
        test: /\.jsx?/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel-loader',
        query: {
          presets: ['react', ['es2015', { modules: false }], 'stage-0'],
        },
      },
      {
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        use: [
          {
            loader: 'babel-loader',
            query: {
              presets: ['react', ['es2015', { modules: false }], 'stage-0'],
            },
          }, 'eslint-loader'], // loader for using js with RegEx against all js files
      }, {
        test: /\.json$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'json-loader',
      }, {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({ loader: 'css-loader', options: { minimize: true } }),
      }, {
        test: webpackIsomorphicToolsPlugin.regular_expression('images'),
        use: [
          {
            loader: 'url-loader',
            options: { limit: 40000 },
          },
          'image-webpack-loader',
        ],
      },
    ],
  },
};

```

**Comment by catamphetamine** [comment]
What's the exact issue you're having

**Comment by rahulbasu710** [comment]
The problem is when I am building it builds fine, but on running it using npm run start it throws an error in the console saying exports not defined Reference Error for my vendor and bundle js files.

I followed the readme of the library and did the steps and the rest of the project was running fine before adding the library. One thing though, in my Html.js I have removed store from the example. Rest is same as the readme. The error only comes in browser console.

**Comment by catamphetamine** [comment]
Post the exact error

**Comment by catamphetamine** [comment]
That's something with your `vendor.js` file.
Perhaps you aren't creating it the right way (whichever it is).

**Comment by rahulbasu710** [comment]
Thanks man. Ryt, so I added the babel-preset-env and that seemed to solve the earlier error but now I get this on starting the browser

Error in Terminal
```
GET / 500 9.501 ms - 148
Invariant Violation: Minified React error #46; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=46 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at reactProdInvariant (/Users/rahulbasu/Desktop/repository/subway_style/node_modules/react-dom/lib/reactProdInvariant.js:31:15)
    at renderToString (/Users/rahulbasu/Desktop/repository/subway_style/node_modules/react-dom/lib/ReactServerRendering.js:72:152)
    at Html (/Users/rahulbasu/Desktop/repository/subway_style/src/Html.js:32:58)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/Users/rahulbasu/Desktop/repository/subway_style/node_modules/react-dom/lib/ReactCompositeComponent.js:308:14)
    at ReactCompositeComponentWrapper._constructComponent (/Users/rahulbasu/Desktop/repository/subway_style/node_modules/react-dom/lib/ReactCompositeComponent.js:284:19)
    at ReactCompositeComponentWrapper.mountComponent (/Users/rahulbasu/Desktop/repository/subway_style/node_modules/react-dom/lib/ReactCompositeComponent.js:187:21)
    at Object.mountComponent (/Users/rahulbasu/Desktop/repository/subway_style/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at /Users/rahulbasu/Desktop/repository/subway_style/node_modules/react-dom/lib/ReactServerRendering.js:45:36
    at ReactServerRenderingTransaction.perform (/Users/rahulbasu/Desktop/repository/subway_style/node_modules/react-dom/lib/Transaction.js:143:20)
    at renderToStringImpl (/Users/rahulbasu/Desktop/repository/subway_style/node_modules/react-dom/lib/ReactServerRendering.js:43:24)
```

**Comment by rahulbasu710** [comment]
Is there an example of usage with this library you can reference me to?

**Comment by catamphetamine** [comment]
This, for example
https://github.com/erikras/react-redux-universal-hot-example/blob/master/webpack/webpack-isomorphic-tools.js#L64-L96

**Comment by rahulbasu710** [comment]
Thanks for all your help man. I found one in your readme. I shall follow it!

**Comment by catamphetamine** [comment]
And `universal-webpack` is still the best practice.
Although people tend to use `Next.js` 2.0 nowadays so perhaps you should even skip both `universal-webpack` and this repo and try `Next.js`

**Comment by rahulbasu710** [comment]
Wow that's a great advice. We can connect on Gitter sometime and am sure I will need your help further

Thanks
