### ISSUE TITLE
Depreciation for webpack 4x

### ISSUE THREAD

**Issue by tavurth** [catamphetamine/webpack-isomorphic-tools#156]
```
(node:6433) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at Webpack_isomorphic_tools_plugin.apply (/home/william/projects/frontend/node_modules/webpack-isomorphic-tools/source/plugin/plugin.js:152:11)
    at webpack (/home/william/projects/frontend/node_modules/webpack/lib/webpack.js:37:12)
    at Object.<anonymous> (/home/william/projects/frontend/server/webpack/server.dev.js:9:25)
    at Module._compile (module.js:652:30)
    at loader (/home/william/projects/frontend/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/william/projects/frontend/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

**Comment by tavurth** [comment]
@catamphetamine We've been looking to move away from `webpack-isomorphic-tools` in any case, so this will provide a good incentive. Thank you for the advice!
